#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys


ROOT_FILES = ("src", "app")
PROC_RE = re.compile(r"^[ \t]*(subroutine|function)[ \t]+([a-z0-9_]+)", re.IGNORECASE)
USE_RE = re.compile(r"^[ \t]*use[ \t]+([a-z0-9_]+)", re.IGNORECASE)

UNIT_PROCS = {
    "empty_char",
    "alltospace",
    "strlength",
    "parse_spaces",
    "eulerrmat",
    "compcart",
    "eulerfixed",
    "setcell",
    "icell_to_cell",
    "index_cell",
    "init_random_number",
    "seed_from_time",
    "flash1",
    "i4hex",
    "i5hex",
    "gp_ieee_signal1",
    "gp_ieee_signal2",
    "shrink",
    "expand",
    "evalhd",
}

COMPONENT_PROCS = {
    "parse_command",
    "get_filename",
    "parse_command_line_args",
    "setsizes",
    "cenmass",
    "resetcells",
    "checkpoint",
    "printbar",
    "getinp",
    "failopen",
    "setrnum",
    "setcon",
    "getkeywords",
    "chainc",
    "clear",
    "comprest",
    "gwalls",
    "gparc",
    "computef",
    "computeg",
    "comparegrad",
    "discret",
    "initial",
    "swaptype",
    "movebad",
    "restmol",
    "writesuccess",
    "output",
    "write_connect",
    "pgencan",
    "packmolprecision",
    "tobar",
    "title",
}

GENCAN_PROCS = {
    "evalal",
    "evalnal",
    "evalhd",
    "easygencan",
    "gencan",
    "spgls",
    "cg",
    "tnls",
    "calcf",
    "calcg",
    "calcgdiff",
    "calchd",
    "calchddiff",
    "shrink",
    "expand",
    "evalnaldiff",
}

CHECKLIST_INTRO = """# Procedure Test Checklist

This file is generated by `scripts/generate_inventory.py`. It classifies every discovered Fortran procedure and records the intended test strategy for Packmol's baseline test suite.
"""


def collect_procedures(root: pathlib.Path) -> list[dict[str, object]]:
    procedures: list[dict[str, object]] = []
    for folder in ROOT_FILES:
        for path in sorted((root / folder).glob("*.f*")):
            uses = []
            for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
                use_match = USE_RE.match(line)
                if use_match:
                    uses.append(use_match.group(1).lower())
                proc_match = PROC_RE.match(line)
                if proc_match:
                    name = proc_match.group(2).lower()
                    procedures.append(
                        {
                            "procedure": name,
                            "source_file": str(path.relative_to(root)),
                            "kind": proc_match.group(1).lower(),
                            "category": classify(name, str(path.relative_to(root))),
                            "dependencies": sorted(set(uses)),
                            "test_type": test_type(name, str(path.relative_to(root))),
                            "shim_required": shim_required(name, str(path.relative_to(root))),
                        }
                    )
    return procedures


def classify(name: str, source_file: str) -> str:
    if name in GENCAN_PROCS or source_file.endswith("gencan.f"):
        return "optimizer-internal"
    if name in UNIT_PROCS:
        return "unit"
    return "component"


def test_type(name: str, source_file: str) -> str:
    if name in UNIT_PROCS:
        return "direct-unit"
    if name in {"parse_command", "get_filename", "parse_command_line_args"}:
        return "subprocess"
    if source_file.endswith("gencan.f"):
        return "smoke-or-component"
    return "component"


def shim_required(name: str, source_file: str) -> bool:
    if name in UNIT_PROCS and not source_file.endswith("output.f90"):
        return False
    return source_file.endswith("gencan.f") or name not in UNIT_PROCS


def write_outputs(root: pathlib.Path, procedures: list[dict[str, object]]) -> None:
    inv_dir = root / "tests" / "inventory"
    inv_dir.mkdir(parents=True, exist_ok=True)
    json_path = inv_dir / "procedures.json"
    md_path = inv_dir / "CHECKLIST.md"
    json_path.write_text(json.dumps(procedures, indent=2) + "\n", encoding="utf-8")

    grouped: dict[str, list[dict[str, object]]] = {}
    for proc in procedures:
        grouped.setdefault(proc["category"], []).append(proc)
    lines = [CHECKLIST_INTRO, ""]
    for category in ("unit", "component", "optimizer-internal"):
        lines.append(f"## {category}")
        for proc in grouped.get(category, []):
            lines.append(
                f"- `{proc['procedure']}` in `{proc['source_file']}`: "
                f"{proc['test_type']}, shim_required={str(proc['shim_required']).lower()}"
            )
        lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")


def check_outputs(root: pathlib.Path, procedures: list[dict[str, object]]) -> int:
    inv_dir = root / "tests" / "inventory"
    json_path = inv_dir / "procedures.json"
    md_path = inv_dir / "CHECKLIST.md"
    if not json_path.exists() or not md_path.exists():
        print("inventory files are missing; run scripts/generate_inventory.py --write", file=sys.stderr)
        return 1
    expected_json = json.dumps(procedures, indent=2) + "\n"
    if json_path.read_text(encoding="utf-8") != expected_json:
        print("inventory JSON is stale; run scripts/generate_inventory.py --write", file=sys.stderr)
        return 1
    generated_md = []
    grouped: dict[str, list[dict[str, object]]] = {}
    for proc in procedures:
        grouped.setdefault(proc["category"], []).append(proc)
    generated_md.extend([CHECKLIST_INTRO, ""])
    for category in ("unit", "component", "optimizer-internal"):
        generated_md.append(f"## {category}")
        for proc in grouped.get(category, []):
            generated_md.append(
                f"- `{proc['procedure']}` in `{proc['source_file']}`: "
                f"{proc['test_type']}, shim_required={str(proc['shim_required']).lower()}"
            )
        generated_md.append("")
    if md_path.read_text(encoding="utf-8") != "\n".join(generated_md):
        print("inventory checklist is stale; run scripts/generate_inventory.py --write", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path("."))
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not args.write and not args.check:
        parser.error("one of --write or --check is required")

    procedures = collect_procedures(args.root)
    if args.write:
        write_outputs(args.root, procedures)
        return 0
    return check_outputs(args.root, procedures)


if __name__ == "__main__":
    raise SystemExit(main())
